[connections.snowpark]
account = ""
user = ""
password = ""
role = "ACCOUNTADMIN"
warehouse = "XXLARGE_WH"
database = "SNOWFLAKE_SAMPLE_DATA"
schema = "TPCDS_SF10TCL"
client_session_keep_alive = true
