[connections.snowpark]
account = "sodqcyd-wtb96023"
user = "shiva123"
password = "My1Cloud"
role = "ACCOUNTADMIN"
warehouse = "XXLARGE_WH"
database = "SNOWFLAKE_SAMPLE_DATA"
schema = "TPCDS_SF10TCL"
client_session_keep_alive = true
